apiVersion: v1
kind: Template
metadata:
  name: project-name-config-template
objects:
parameters:
- description: Application Name
  displayName: Application Name
  name: APP_NAME
  required: true
  value: autorizaciones-api
